packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@trpc/server": ^11.7.2
  "@types/express": ^5.0.1
  "@trpc/client": ^11.7.2
  "@prisma/client": ^7.1.0
